import { AgentTableResponse } from '../agent/agent-table-response.model';

export interface CustomerResponse {
  id: string;
  name: string;
  alias?: string;
  ledgerName?: string;
  printName?: string;
  groupName?: string;
  gstIn?: string;
  pan?: string;
  regType?: number;
  discount?:number;
  mu?: number;
  paymentTerm?: number;
  customerCategory?: number;
  customerStatus?: number;
  rateType?: number;
  alternateNo?: string;
  creditAlertLimit?: number;
  incentive?: number;
  term?: number;
  reference?: string;
  customerCode?: string;
  billingAddress?: string;
  shippingAddress?: string;
  cityName: string;
  stateId:number;
  stateName: string;
  stateCode: string;
  pinCode?: string;
  phone?: string;
  mobile?: string;
  email?: string;
  contactPerson?: string;
  openingBalance?: number;
  creditDays?: number;
  creditLimit?: number;
  priceLevel?: number;
  tallyLedgerType?: number;
  tallyCategory?: number;
  customerType: number;
  transportId?: number;
  customerAgentId?: string;
  customerAgentObj?: AgentTableResponse;
  remarks?: string;
  isActive: boolean;
}
