export interface CustomerResponse {
  id: string;
  name: string;
  alias?: string;
  ledgerName?: string;
  printName?: string;
  groupName?: string;
  gstIn?: string;
  pan?: string;
  regType?: number;
  discount?:number;
  mu?: number;
  paymentTerm?: number;
  customerCategory?: number;
  billingAddress?: string;
  shippingAddress?: string;
  cityName: string;
  stateId:number;
  stateName: string;
  stateCode: string;
  pinCode?: string;
  phone?: string;
  mobile?: string;
  email?: string;
  contactPerson?: string;
  openingBalance?: number;
  creditDays?: number;
  creditLimit?: number;
  priceLevel?: number;
  tallyLedgerType?: number;
  tallyCategory?: number;
  customerType: number;
  remarks?: string;
  isActive: boolean;
}
